<!DOCTYPE html>
<html>
<head>
    <title>My Shop</title>
</head>
<body>
<h1>My Shop</h1><hr>
<h4>Panel of administrator</h4><hr>

<p><a href="/admin/clients">Clients</a></p>
<br>
<p><a href="/admin/goods">Goods</a></p>
<br>
<p><a href="/admin/orders">Orders</a></p>
<br>
<p><a href="/admin/categories">Categories</a></p>
<br>
<p><a href="/admin/payments">Payments</a> </p>
<br>
<p><a href="/admin/receiving">Receiving</a> </p>
<br>
<p><a href="/admin/statuses">Statuses</a> </p>
<br>
<form action="/" method="get">
    <input type="submit" value="To main page"/>
</form>
</body>
</html>