create table bank_cards (
    id          int4 generated by default as identity not null,
    version     int4,
    back_number int2 not null,
    month       int2 not null,
    number      varchar(255) not null,
    year        int2 not null,
    client_id   int4 not null,
    primary key (id)
);

create table categories
(
    id      int4 generated by default as identity not null,
    version int4,
    name    varchar(255) not null,
    primary key (id)
);

create table clients
(
    id       int4 generated by default as identity not null,
    version  int4,
    email    varchar(255) not null,
    name     varchar(255) not null,
    password varchar(255) not null,
    phone    varchar(255),
    role     varchar(255) not null,
    primary key (id)
);

create table goods
(
    id           int4 generated by default as identity not null,
    version      int4,
    count        int8 not null,
    image_url    varchar(255) not null,
    name         varchar(255) not null,
    price        numeric(19, 2) not null,
    category_id  int4 not null,
    producer_id  int4 not null,
    primary key (id)
);

create table orders
(
    id           int4 generated by default as identity not null,
    version      int4,
    bill_status  varchar(255) not null,
    order_status varchar(255) not null,
    payment_type varchar(255),
    total_price  numeric(19, 2) not null,
    receive_id   int4,
    client_id    int4 not null,
    primary key (id)
);

create table producers
(
    id            int4 generated by default as identity not null,
    version       int4,
    country       varchar(255) not null,
    producer_name varchar(255) not null,
    primary key (id)
);

create table receivings
(
    id             int4 generated by default as identity not null,
    version        int4,
    address        varchar(255) not null,
    receive_method varchar(255) not null,
    primary key (id)
);

create table selected_products
(
    id       int4 generated by default as identity not null,
    version  int4,
    count    int8 not null,
    price    numeric(19, 2) not null,
    goods_id int4 not null,
    order_id int4 not null,
    primary key (id)
);

alter table if exists bank_cards
    add constraint bankCard_clientId_ref
    foreign key (client_id)
    references clients;

alter table if exists goods
    add constraint goods_categoryId_ref
    foreign key (category_id)
    references categories;

alter table if exists goods
    add constraint goods_producerId_ref
    foreign key (producer_id)
    references producers;

alter table if exists orders
    add constraint orders_receiveId_ref
    foreign key (receive_id)
    references receivings;

alter table if exists orders
    add constraint orders_clientId_ref
    foreign key (client_id)
    references clients;

alter table if exists selected_products
    add constraint selectedProducts_goodsId_ref
    foreign key (goods_id)
    references goods;

alter table if exists selected_products
    add constraint selectedProducts_orderId_ref
    foreign key (order_id)
    references orders;

INSERT INTO producers (producer_name, country)VALUES ('Philips', 'Netherlands');

INSERT INTO producers (producer_name, country)VALUES ('Sven', 'Russia');

INSERT INTO categories (name) VALUES ('headphones');

INSERT INTO categories (name) VALUES ('hair clipper');

INSERT INTO receivings (receive_Method, address) VALUES ('pickup', 'Kazan, Mavlytovo, 35a');

INSERT INTO receivings (receive_Method, address) VALUES ('pickup', 'Kazan, Mavlytovo, 10');

INSERT INTO clients (email, name, password, phone, role) VALUES ('username@bk.ru', 'myUserName', '$2a$10$qE8dBirGs7TCdkI8bAZpg.N9Go38.vkxteGP.J12D51brnd2egNpC', '89873141130','USER');

INSERT INTO goods (name, price, producer_id, category_id, count, image_url) VALUES ('Sven 35 AVG', 2500, 1, 1, 10, 'https://www.sven.fi/upload/iblock_photos/headsets/ap-940mv/003-photo-big.jpg');

INSERT INTO goods (name, price, producer_id, category_id, count, image_url) VALUES ('Philips A10', 2000, 2, 2, 5, 'https://avatars.mds.yandex.net/get-mpic/4737085/img_id9089403824290607173.jpeg/orig');